# Configuración de Servidor Quarkus
quarkus.http.port=${BACKEND_PORT:8080}
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS, HEAD

# Conexión Oficial a Neo4j 5.x
quarkus.neo4j.uri=${NEO4J_URI:bolt://localhost:7687}
quarkus.neo4j.authentication.username=${NEO4J_USERNAME:neo4j}
quarkus.neo4j.authentication.password=${NEO4J_PASSWORD}

# Configuración de Seguridad SmallRye JWT
mp.jwt.verify.issuer=${JWT_ISSUER:https://yaga-social.com/issuer}
quarkus.smallrye-jwt.enabled=true

# Configuración de RustFS / S3
rustfs.endpoint=${RUSTFS_ENDPOINT:http://localhost:9000}
rustfs.access-key=${RUSTFS_ACCESS_KEY}
rustfs.secret-key=${RUSTFS_SECRET_KEY}
rustfs.bucket=${RUSTFS_BUCKET:social-media-assets}
